#!/bin/bash

echo "To create a GitHub repository for this project:"
echo "=============================================="
echo ""
echo "Option 1: Using GitHub website"
echo "1. Go to https://github.com/new"
echo "2. Repository name: econtrol_extractor"
echo "3. Description: Apify actor for extracting E-Control data using Austrian postal codes"
echo "4. Make it public or private as needed"
echo "5. DON'T initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "Then run these commands:"
echo "git remote add origin https://github.com/YOUR_USERNAME/econtrol_extractor.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Option 2: Install GitHub CLI first"
echo "1. Install: brew install gh"
echo "2. Login: gh auth login"
echo "3. Create repo: gh repo create econtrol_extractor --public --source=. --push"
echo ""